import type { DemoStep } from "../types";

export const leadsSteps: DemoStep[] = [
  {
    id: "leads-intro",
    module: "leads",
    title: "Lead Workspace",
    body: "The lead workspace is where the relationship comes together. We're carrying the same lead forward from the dashboard so you can see how the CRM keeps context in one place.",
    beforeShow: [
      { type: "waitFor", target: "[data-demo='lead-drawer']", timeoutMs: 12000 },
    ],
  },
  {
    id: "leads-drawer-overview",
    module: "leads",
    title: "Relationship Record",
    body: "This drawer is the hub for the banker workflow: contact details, pipeline stage, value, recent work, and the next recommended action. Most rep activity starts here.",
    target: "lead-drawer-header",
    placement: "left",
    beforeShow: [
      { type: "waitFor", target: "[data-demo='lead-drawer-header']", timeoutMs: 12000 },
    ],
  },
  {
    id: "leads-workflow-links",
    module: "leads",
    title: "Navigate The Same Lead Across The CRM",
    body: "These shortcuts keep the rep on the same relationship as they move between modules. Instead of hunting through lists, the CRM carries the lead context with you.",
    target: "lead-workflow-links",
    placement: "left",
    beforeShow: [
      { type: "waitFor", target: "[data-demo='lead-workflow-links']", timeoutMs: 12000 },
    ],
  },
  {
    id: "leads-tab-activity",
    module: "leads",
    title: "Log The Latest Touchpoint",
    body: "The activity tab is where a rep records the call, email, meeting, or note that just happened. Logging it immediately keeps the record current for the next banker who opens the lead.",
    target: "lead-tab-activity",
    targetAttr: "data-tour",
    placement: "bottom",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-set-detail-tab", detail: "activity" },
      { type: "waitFor", target: "[data-demo='lead-activity-quick-log']", timeoutMs: 8000 },
    ],
  },
  {
    id: "leads-activity-quick-log",
    module: "leads",
    title: "Quick Activity Logging",
    body: "Reps do not need to leave the lead to capture the latest interaction. The quick-log card keeps the rhythm simple: record the touchpoint, then move straight into the next action.",
    target: "lead-activity-quick-log",
    placement: "left",
    skipIf: "[data-demo='lead-activity-quick-log']",
  },
  {
    id: "leads-tab-contacts",
    module: "leads",
    title: "Track The Relationship Team",
    body: "Switching to Contacts shows everyone tied to this opportunity. That keeps the rep focused on the real buying group, not just one inbox thread.",
    target: "lead-tab-contacts",
    targetAttr: "data-tour",
    placement: "bottom",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-set-detail-tab", detail: "contacts" },
      { type: "waitFor", target: "[data-tour='lead-tab-contacts']", timeoutMs: 8000 },
    ],
  },
  {
    id: "leads-contacts-form",
    module: "leads",
    title: "Add Stakeholders Without Leaving The Lead",
    body: "Use this form to add decision-makers, operators, or support contacts as soon as they appear in the sales cycle. That way the next call starts with the full relationship map already in place.",
    target: "lead-contacts-form",
    placement: "left",
    skipIf: "[data-demo='lead-contacts-form']",
  },
  {
    id: "leads-search",
    module: "leads",
    title: "Find Any Lead Fast",
    body: "When the rep is not working from the queue, search and filters make it easy to pull up the right relationship by name, company, stage, or ownership.",
    target: "leads-search",
    targetAttr: "data-tour",
    placement: "bottom",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-set-detail-tab", detail: "activity" },
      { type: "dispatch", value: "crm-tour-close-drawer" },
      { type: "wait", value: "350" },
      { type: "waitFor", target: "[data-tour='leads-search']", timeoutMs: 8000 },
    ],
  },
  {
    id: "leads-ai-search",
    module: "leads",
    title: "Natural-Language Search",
    body: "AI search lets the rep ask for a working list in plain language, like leads with follow-up due this week or prospects with no recent activity. It is a faster way to recover work that would otherwise live in Outlook folders.",
    target: "leads-ai-toggle",
    targetAttr: "data-tour",
    placement: "bottom",
  },
  {
    id: "leads-status-filter",
    module: "leads",
    title: "Tighten The Pipeline View",
    body: "Standard filters still matter. A rep can narrow by stage, branch, rep, and date to get a focused worklist before opening the next relationship.",
    target: "leads-status-filter",
    targetAttr: "data-tour",
    placement: "bottom",
  },
  {
    id: "leads-prep-link",
    module: "leads",
    title: "Open The Prep Brief",
    body: "Before a call or meeting, the rep can launch a prep brief directly from the lead record. We'll open that same lead next so the story stays connected.",
    target: "lead-prep-button",
    targetAttr: "data-tour",
    placement: "left",
    beforeShow: [
      { type: "dispatch", value: "crm-demo-open-primary-lead" },
      { type: "waitFor", target: "[data-tour='lead-prep-button']", timeoutMs: 12000 },
    ],
    afterDismiss: [
      { type: "dispatch", value: "crm-demo-navigate-prep" },
      { type: "wait", value: "250" },
    ],
  },
];
