import type { DemoStep } from "../types";

export const shellSteps: DemoStep[] = [
  {
    id: "shell-welcome",
    module: "shell",
    title: "Welcome to the Deerwood Bank CRM Demo!",
    body: "This guided demo walks you through every major feature of the platform. It's organized by module - you can pause anytime, skip sections, or restart from the Demo button. Let's begin with the app shell.",
  },
  {
    id: "shell-sidebar-core",
    module: "shell",
    title: "Core Navigation",
    body: "The sidebar is your home base. These four items - Dashboard, Leads, Contacts, and Activities - are available to every user regardless of role.",
    target: "nav-dashboard",
    targetAttr: "data-tour",
    placement: "right",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-open-sidebar" },
      { type: "wait", value: "300" },
    ],
  },
  {
    id: "shell-sidebar-tools",
    module: "shell",
    title: "Tools Section",
    body: "Below the core items, the Tools group gives you Ticklers (follow-up reminders), a geographic Map view, and the Import tool for bringing in new leads from spreadsheets.",
    target: "nav-ticklers",
    targetAttr: "data-tour",
    placement: "right",
  },
  {
    id: "shell-sidebar-reporting",
    module: "shell",
    title: "Reporting & Admin",
    body: "Managers and admins see additional items here: Reports for pipeline analytics, and Automations for workflow rules. These are role-gated - sales reps won't see them.",
    target: "nav-settings",
    targetAttr: "data-tour",
    placement: "right",
    skipIf: "[data-tour='nav-settings']",
  },
  {
    id: "shell-sidebar-collapse-show",
    module: "shell",
    title: "Collapse Sidebar",
    body: "This button collapses the sidebar to icon-only mode for more screen space. Watch - we'll collapse it now.",
    target: "sidebar-collapse",
    placement: "right",
    afterDismiss: [
      { type: "click", target: "[data-demo='sidebar-collapse']" },
      { type: "wait", value: "400" },
    ],
  },
  {
    id: "shell-sidebar-collapsed",
    module: "shell",
    title: "Collapsed View",
    body: "Now the sidebar shows only icons - hover any icon to see its label. This gives you maximum workspace. Let's expand it back.",
    target: "sidebar-collapse",
    placement: "right",
  },
  {
    id: "shell-sidebar-expanded",
    module: "shell",
    title: "Sidebar Restored",
    body: "Back to the full sidebar. In Teams mode, it starts collapsed automatically to save space. Now let's look at the header.",
    target: "sidebar-collapse",
    placement: "right",
    afterDismiss: [
      { type: "click", target: "[data-demo='sidebar-collapse']" },
      { type: "wait", value: "400" },
    ],
  },
  {
    id: "shell-header-profile",
    module: "shell",
    title: "Your Profile",
    body: "The header shows your name, email, and role. On the right you'll find the notification bell and your role badge.",
    target: "header-profile",
    placement: "bottom",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-close-sidebar" },
      { type: "wait", value: "200" },
    ],
  },
  {
    id: "shell-notifications-bell",
    module: "shell",
    title: "Notification Bell",
    body: "The bell icon shows your unread notification count. When you have new alerts, a red badge appears. Let's click it to see your notifications.",
    target: "header-notifications",
    placement: "bottom",
    afterDismiss: [
      { type: "dispatch", value: "crm-demo-open-notifications" },
      { type: "wait", value: "400" },
    ],
  },
  {
    id: "shell-notifications-panel",
    module: "shell",
    title: "Your Notifications",
    body: "Here's your notification panel. It shows automation alerts, follow-up reminders, and system messages. You can mark individual items as read by clicking them, or use 'Mark all as read' at the top.",
    target: "notifications-panel",
    placement: "left",
    beforeShow: [
      { type: "waitFor", target: "[data-demo='notifications-panel']", timeoutMs: 8000 },
      { type: "wait", value: "400" },
    ],
    afterDismiss: [
      { type: "dispatch", value: "crm-demo-close-notifications" },
      { type: "wait", value: "200" },
    ],
  },
  {
    id: "shell-signout",
    module: "shell",
    title: "Sign Out",
    body: "The Sign Out button is at the bottom of the sidebar. In Teams mode, sign-out is handled by Teams itself. Now let's move on to the Dashboard!",
    target: "sign-out",
    placement: "right",
    beforeShow: [
      { type: "dispatch", value: "crm-tour-open-sidebar" },
      { type: "wait", value: "300" },
    ],
  },
];
