import type { UserRole } from "../types";

export interface TourStep {
  id: string;
  route: string;
  target?: string;
  title: string;
  body: string;
  placement?: "top" | "bottom" | "left" | "right";
  requiredRoles?: UserRole[];
}

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome",
    route: "/dashboard",
    title: "Welcome to Deerwood Bank CRM!",
    body: "Let\u2019s take a quick tour of the platform. This will only take a couple of minutes. You can skip anytime or resume later.",
  },
  {
    id: "dashboard-stats",
    route: "/dashboard",
    target: "dashboard-stats",
    title: "Your Key Metrics",
    body: "These cards show your active leads, pipeline value, wins, and conversion rate at a glance.",
    placement: "bottom",
  },
  {
    id: "dashboard-pipeline",
    route: "/dashboard",
    target: "dashboard-pipeline",
    title: "Pipeline Funnel",
    body: "See how your leads are distributed across each stage of the sales pipeline.",
    placement: "bottom",
  },
  {
    id: "dashboard-followups",
    route: "/dashboard",
    target: "dashboard-followups",
    title: "Follow-Ups & Leaderboard",
    body: "Never miss a follow-up. Overdue, today, and upcoming items are highlighted here.",
    placement: "top",
  },
  {
    id: "nav-leads",
    route: "/dashboard",
    target: "nav-leads",
    title: "Leads Page",
    body: "This is where you manage all your leads. Let\u2019s head there now.",
    placement: "right",
  },
  {
    id: "leads-search",
    route: "/leads",
    target: "leads-search",
    title: "Search Leads",
    body: "Quickly find any lead by name, company, email, or phone. Try Ctrl+K as a shortcut!",
    placement: "bottom",
  },
  {
    id: "leads-ai-toggle",
    route: "/leads",
    target: "leads-ai-toggle",
    title: "AI-Powered Search",
    body: "Toggle this to search in plain language, like \u201cdormant referral leads assigned to John.\u201d",
    placement: "bottom",
  },
  {
    id: "leads-status-filter",
    route: "/leads",
    target: "leads-status-filter",
    title: "Filter by Status",
    body: "Narrow down leads by pipeline stage: Prospect, Contacted, Qualified, and more.",
    placement: "bottom",
  },
  {
    id: "lead-first-row",
    route: "/leads",
    target: "lead-first-row",
    title: "Open a Lead",
    body: "Click any row to open the lead detail drawer. We\u2019ll open one for you.",
    placement: "bottom",
  },
  {
    id: "lead-tab-activity",
    route: "/leads",
    target: "lead-tab-activity",
    title: "Activity Tab",
    body: "View all calls, emails, meetings, and notes for this lead. Log new activities here too.",
    placement: "bottom",
  },
  {
    id: "lead-tab-contacts",
    route: "/leads",
    target: "lead-tab-contacts",
    title: "Contacts Tab",
    body: "See all contacts associated with this lead \u2014 decision makers, influencers, and more.",
    placement: "bottom",
  },
  {
    id: "lead-prep-button",
    route: "/leads",
    target: "lead-prep-button",
    title: "AI Prep Sheet",
    body: "Generate an AI-powered briefing before your next call or meeting with this lead.",
    placement: "left",
  },
  {
    id: "prep-brief",
    route: "/prep",
    target: "prep-brief",
    title: "Your AI Brief",
    body: "This is the AI-generated prep sheet with context, talking points, and recommendations.",
    placement: "bottom",
  },
  {
    id: "nav-contacts",
    route: "/prep",
    target: "nav-contacts",
    title: "Contacts Page",
    body: "Manage all your contacts across leads in one central place.",
    placement: "right",
  },
  {
    id: "contacts-overview",
    route: "/contacts",
    target: "contacts-overview",
    title: "Contact Management",
    body: "Search, filter, and manage contacts. Each contact is linked to a lead for full context.",
    placement: "top",
  },
  {
    id: "nav-activities",
    route: "/contacts",
    target: "nav-activities",
    title: "Activities Page",
    body: "Track all your sales activities in one view.",
    placement: "right",
  },
  {
    id: "activities-view-toggle",
    route: "/activities",
    target: "activities-view-toggle",
    title: "Timeline & Calendar",
    body: "Switch between a chronological timeline and a calendar view of your activities.",
    placement: "bottom",
  },
  {
    id: "nav-ticklers",
    route: "/activities",
    target: "nav-ticklers",
    title: "Ticklers",
    body: "Set reminders and recurring tasks so nothing falls through the cracks.",
    placement: "right",
  },
  {
    id: "ticklers-overview",
    route: "/ticklers",
    target: "ticklers-overview",
    title: "Your Reminders",
    body: "Organized by Overdue, Today, Upcoming, and Done. Create, snooze, or complete ticklers here.",
    placement: "top",
  },
  {
    id: "nav-map",
    route: "/ticklers",
    target: "nav-map",
    title: "Prospect Map",
    body: "Visualize your leads geographically.",
    placement: "right",
  },
  {
    id: "map-overview",
    route: "/map",
    target: "map-overview",
    title: "Geographic View",
    body: "See all your leads on a map. Filter by branch, rep, or status to focus on specific areas.",
    placement: "top",
  },
  {
    id: "nav-settings",
    route: "/map",
    target: "nav-settings",
    title: "Settings",
    body: "Customize your CRM experience.",
    placement: "right",
  },
  {
    id: "settings-preferences",
    route: "/settings",
    target: "settings-preferences",
    title: "Your Preferences",
    body: "Set your default branch, leads per page, and notification preferences here.",
    placement: "top",
  },
  {
    id: "completion",
    route: "/settings",
    title: "You\u2019re All Set!",
    body: "You\u2019ve seen the key features of Deerwood Bank CRM. You can restart this tour anytime from Settings. Happy selling!",
  },
];
